import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Authorization",
    template: "%s | Authorization",
  },
  description: "Generated by Next.js",
};
export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
