"use client";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: {
//     default: "Welcome to Next.js Learning Session",
//     template: "%s | NextJS Practice",
//   },
//   description: "Generated by create next app",
// };

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>{children}</div>
    </>
  );
}
